apiVersion: v1
kind: Service
metadata:
  name: hello-world-frontend-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    app: hello-world-frontend 