name: Deploy to Cloudlab

on:
  workflow_dispatch:
    inputs:
      experiment_name:
        description: 'Name for the Cloudlab experiment'
        required: true
        type: string
        default: 'hello-world-cluster-test'
      node_count:
        description: 'Number of nodes to provision'
        required: true
        type: number
        default: 1

jobs:
  deploy:
    uses: CampusConnectWCU/Cloudlab-Workflow/.github/workflows/cloudlab-automation.yml@main
    with:
      cloudlab_pem: ${{ secrets.CLOUDLAB_PEM }}
      profile_name: "hello-world-cluster"
      experiment_name: ${{ github.event.inputs.experiment_name || 'hello-world-cluster-test' }}
      node_count: ${{ github.event.inputs.node_count || 1 }}
      username: "ubuntu" 
    secrets:
      inherit: true 
